### ISSUE TITLE
call recorder issue

### ISSUE THREAD

**Issue by ashish12s3** [omnirom/android_device_oneplus_oneplus3#2]
this rom has issue . There is not any option to record call  very low facility in dialer(Phone)
 application

**Comment by rlcDev** [comment]
Absence of a feature is not an issue, I guess. Issue = bug. However, you can download a phone app doing that.

**Comment by xplodwild** [comment]
As rlcDev said, this is not an issue. We do not currently provide this feature, and it is available in multiple third-party apps.
